#!/usr/bin/env python

import os
import sys
import argparse
import seaborn as sns
import matplotlib.pyplot as plt
import pybio
import pybio.core

version = "0.3"

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('commands', help="which command to run?", nargs='*')
parser.add_argument("-fdr", "--fdr", help="FDR threshold, default no filter", default=None, type=float)
parser.add_argument("-logFC", "--logFC", help="logFC threshold, default=None (do not use as filter)", default=None, type=float)
parser.add_argument("-dpfi", "--dpfi", help="delta(percentage feature inclusion) threshold, default=None (do not use as filter)", default=None, type=float)
parser.add_argument("-version", "--version", help="Print version", action="store_true")
args = parser.parse_args()

if args.version:
    print(f"pybio v{version}, https://github.com/grexor/pybio")
    print("---")

if len(args.commands)>0:

    if args.commands[0]=="annotate":
        print("pybio annotate")

    if args.commands[0]=="ensembl":
        print("pybio ensembl")
        species = args.commands[1]
        try:
            ensembl_version = args.commands[2]
        except:
            ensembl_version = pybio.config.ensembl_latest_version
        #pybio.core.genomes.download(species, ensembl_version)
        pybio.core.genomes.prepare(species, ensembl_version)
        #pybio.core.genomes.star_index(species, ensembl_version)
        #pybio.core.genomes.salmon_index(species, ensembl_version)

"""
        cd $gdir
        rm -r ${species}.assembly.ensembl${eversion}.star
        mkdir ${species}.assembly.ensembl${eversion}.star
        STAR --runMode genomeGenerate --genomeDir ${species}.assembly.ensembl${eversion}.star --genomeFastaFiles ${species}.assembly.ensembl${eversion}/${species}.fasta --runThreadN 4 --sjdbGTFfile ${species}.annotation.ensembl${eversion}/${ensembl_longB[hg38]}.${ensembl_longC[hg38]}.${eversion}.chr.gtf

        gzip -f ${species}.annotation.ensembl${eversion}/${ensembl_longB[hg38]}.${ensembl_longC[hg38]}.${eversion}.chr.gtf # to save space

        rm -r ${species}.transcripts.ensembl${eversion}
        mkdir ${species}.transcripts.ensembl${eversion}
        cd ${species}.transcripts.ensembl${eversion}
        wget ftp://ftp.ensembl.org/pub/release-${eversion}/fasta/${ensembl_longA[hg38]}/cdna/${ensembl_longB[hg38]}.${ensembl_longC[hg38]}.cdna.all.fa.gz

        cd $gdir
        salmon index -t ${species}.transcripts.ensembl${eversion}/${ensembl_longB[hg38]}.${ensembl_longC[hg38]}.cdna.all.fa.gz -i ${species}.transcripts.ensembl${eversion}.salmon
"""