#!/usr/bin/env python

import os
import sys
import argparse
import seaborn as sns
import matplotlib.pyplot as plt
import pybio
import pybio.core

version = "0.3"

print(f"[pybio] v{version}")
print("Github: https://github.com/grexor/pybio")
print()

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('commands', help="which command to run?", nargs='*')
parser.add_argument("-version", "--version", help="Print version", action="store_true")
parser.add_argument("-nostar", "--nostar", help="Do not process genome with STAR (index)", action="store_true")
parser.add_argument("-nosalmon", "--nosalmon", help="Do not process transcripts with salmon (index)", action="store_true")
args = parser.parse_args()

if args.version:
    print(f"pybio v{version}, https://github.com/grexor/pybio")
    print("---")

if len(args.commands)>0:

    if args.commands[0]=="ensembl":
        species = args.commands[1]
        try:
            ensembl_version = args.commands[2]
        except:
            ensembl_version = pybio.config.ensembl_version_latest            
        pybio.genome_download_prepare(species, ensembl_version, args)

